### ISSUE TITLE
srt format

### ISSUE THREAD

**Issue by serramat** [MRdotB/yifysubtitles#2]
Hi,
is it possibile to add an option on yifysubtitles call (like paths, langs...) to download the subtitles in srt format instead vvt?
Thanks.

**Comment by MRdotB** [comment]
Hi, yes it's possible I'm going to do it today.

**Comment by MRdotB** [comment]
Added to option. [2.1.2](https://github.com/MRdotB/yifysubtitles/commit/3b7c5bed265bfc868bd323e728b93b5a16c7e271)

**Comment by serramat** [comment]
Thanks for the fast update!!!
