### ISSUE TITLE
Value for "Persian" language is "farsi/persian" and not "farsi-persian"

### ISSUE THREAD

**Issue by mohsentaleb** [mrdotb/yifysubtitles#8]
I'm writing a new nodejs module using your lib and realized there's a problem regarding your key/value mapping for languages:

https://github.com/mrdotb/yifysubtitles/blob/75ee9084a1df61776b67f04df98245d375da3c97/langs.json#L14

As you can see in screenshot, I inspected the Persian language row:
![image](https://user-images.githubusercontent.com/628654/69709626-fa9e8e00-1112-11ea-841a-33488d73fdde.png)

**Comment by mrdotb** [comment]
I looked at it so the correct mapping should be ```ir: farsi-persian```
